<?php
defined( 'ABSPATH' ) || exit;

class PC_Data {

    /**
     * Get All Countries (ISO 3166-1 alpha-2)
     * Global standard list. Can be filtered by addons.
     */
    public static function get_countries() {
        $countries = array(
            'AF' => __( 'Afghanistan', 'pascommerce' ),
            'AX' => __( 'Åland Islands', 'pascommerce' ),
            'AL' => __( 'Albania', 'pascommerce' ),
            'DZ' => __( 'Algeria', 'pascommerce' ),
            'AS' => __( 'American Samoa', 'pascommerce' ),
            'AD' => __( 'Andorra', 'pascommerce' ),
            'AO' => __( 'Angola', 'pascommerce' ),
            'AI' => __( 'Anguilla', 'pascommerce' ),
            'AQ' => __( 'Antarctica', 'pascommerce' ),
            'AG' => __( 'Antigua and Barbuda', 'pascommerce' ),
            'AR' => __( 'Argentina', 'pascommerce' ),
            'AM' => __( 'Armenia', 'pascommerce' ),
            'AW' => __( 'Aruba', 'pascommerce' ),
            'AU' => __( 'Australia', 'pascommerce' ),
            'AT' => __( 'Austria', 'pascommerce' ),
            'AZ' => __( 'Azerbaijan', 'pascommerce' ),
            'BS' => __( 'Bahamas', 'pascommerce' ),
            'BH' => __( 'Bahrain', 'pascommerce' ),
            'BD' => __( 'Bangladesh', 'pascommerce' ),
            'BB' => __( 'Barbados', 'pascommerce' ),
            'BY' => __( 'Belarus', 'pascommerce' ),
            'BE' => __( 'Belgium', 'pascommerce' ),
            'BZ' => __( 'Belize', 'pascommerce' ),
            'BJ' => __( 'Benin', 'pascommerce' ),
            'BM' => __( 'Bermuda', 'pascommerce' ),
            'BT' => __( 'Bhutan', 'pascommerce' ),
            'BO' => __( 'Bolivia', 'pascommerce' ),
            'BQ' => __( 'Bonaire, Sint Eustatius and Saba', 'pascommerce' ),
            'BA' => __( 'Bosnia and Herzegovina', 'pascommerce' ),
            'BW' => __( 'Botswana', 'pascommerce' ),
            'BV' => __( 'Bouvet Island', 'pascommerce' ),
            'BR' => __( 'Brazil', 'pascommerce' ),
            'IO' => __( 'British Indian Ocean Territory', 'pascommerce' ),
            'BN' => __( 'Brunei Darussalam', 'pascommerce' ),
            'BG' => __( 'Bulgaria', 'pascommerce' ),
            'BF' => __( 'Burkina Faso', 'pascommerce' ),
            'BI' => __( 'Burundi', 'pascommerce' ),
            'CV' => __( 'Cabo Verde', 'pascommerce' ),
            'KH' => __( 'Cambodia', 'pascommerce' ),
            'CM' => __( 'Cameroon', 'pascommerce' ),
            'CA' => __( 'Canada', 'pascommerce' ),
            'KY' => __( 'Cayman Islands', 'pascommerce' ),
            'CF' => __( 'Central African Republic', 'pascommerce' ),
            'TD' => __( 'Chad', 'pascommerce' ),
            'CL' => __( 'Chile', 'pascommerce' ),
            'CN' => __( 'China', 'pascommerce' ),
            'CX' => __( 'Christmas Island', 'pascommerce' ),
            'CC' => __( 'Cocos (Keeling) Islands', 'pascommerce' ),
            'CO' => __( 'Colombia', 'pascommerce' ),
            'KM' => __( 'Comoros', 'pascommerce' ),
            'CD' => __( 'Congo (Democratic Republic)', 'pascommerce' ),
            'CG' => __( 'Congo (Republic)', 'pascommerce' ),
            'CK' => __( 'Cook Islands', 'pascommerce' ),
            'CR' => __( 'Costa Rica', 'pascommerce' ),
            'HR' => __( 'Croatia', 'pascommerce' ),
            'CU' => __( 'Cuba', 'pascommerce' ),
            'CW' => __( 'Curaçao', 'pascommerce' ),
            'CY' => __( 'Cyprus', 'pascommerce' ),
            'CZ' => __( 'Czech Republic', 'pascommerce' ),
            'DK' => __( 'Denmark', 'pascommerce' ),
            'DJ' => __( 'Djibouti', 'pascommerce' ),
            'DM' => __( 'Dominica', 'pascommerce' ),
            'DO' => __( 'Dominican Republic', 'pascommerce' ),
            'EC' => __( 'Ecuador', 'pascommerce' ),
            'EG' => __( 'Egypt', 'pascommerce' ),
            'SV' => __( 'El Salvador', 'pascommerce' ),
            'GQ' => __( 'Equatorial Guinea', 'pascommerce' ),
            'ER' => __( 'Eritrea', 'pascommerce' ),
            'EE' => __( 'Estonia', 'pascommerce' ),
            'SZ' => __( 'Eswatini', 'pascommerce' ),
            'ET' => __( 'Ethiopia', 'pascommerce' ),
            'FK' => __( 'Falkland Islands', 'pascommerce' ),
            'FO' => __( 'Faroe Islands', 'pascommerce' ),
            'FJ' => __( 'Fiji', 'pascommerce' ),
            'FI' => __( 'Finland', 'pascommerce' ),
            'FR' => __( 'France', 'pascommerce' ),
            'GF' => __( 'French Guiana', 'pascommerce' ),
            'PF' => __( 'French Polynesia', 'pascommerce' ),
            'TF' => __( 'French Southern Territories', 'pascommerce' ),
            'GA' => __( 'Gabon', 'pascommerce' ),
            'GM' => __( 'Gambia', 'pascommerce' ),
            'GE' => __( 'Georgia', 'pascommerce' ),
            'DE' => __( 'Germany', 'pascommerce' ),
            'GH' => __( 'Ghana', 'pascommerce' ),
            'GI' => __( 'Gibraltar', 'pascommerce' ),
            'GR' => __( 'Greece', 'pascommerce' ),
            'GL' => __( 'Greenland', 'pascommerce' ),
            'GD' => __( 'Grenada', 'pascommerce' ),
            'GP' => __( 'Guadeloupe', 'pascommerce' ),
            'GU' => __( 'Guam', 'pascommerce' ),
            'GT' => __( 'Guatemala', 'pascommerce' ),
            'GG' => __( 'Guernsey', 'pascommerce' ),
            'GN' => __( 'Guinea', 'pascommerce' ),
            'GW' => __( 'Guinea-Bissau', 'pascommerce' ),
            'GY' => __( 'Guyana', 'pascommerce' ),
            'HT' => __( 'Haiti', 'pascommerce' ),
            'HM' => __( 'Heard Island and McDonald Islands', 'pascommerce' ),
            'VA' => __( 'Holy See', 'pascommerce' ),
            'HN' => __( 'Honduras', 'pascommerce' ),
            'HK' => __( 'Hong Kong', 'pascommerce' ),
            'HU' => __( 'Hungary', 'pascommerce' ),
            'IS' => __( 'Iceland', 'pascommerce' ),
            'IN' => __( 'India', 'pascommerce' ),
            'ID' => __( 'Indonesia', 'pascommerce' ),
            'IR' => __( 'Iran', 'pascommerce' ),
            'IQ' => __( 'Iraq', 'pascommerce' ),
            'IE' => __( 'Ireland', 'pascommerce' ),
            'IM' => __( 'Isle of Man', 'pascommerce' ),
            'IL' => __( 'Israel', 'pascommerce' ),
            'IT' => __( 'Italy', 'pascommerce' ),
            'JM' => __( 'Jamaica', 'pascommerce' ),
            'JP' => __( 'Japan', 'pascommerce' ),
            'JE' => __( 'Jersey', 'pascommerce' ),
            'JO' => __( 'Jordan', 'pascommerce' ),
            'KZ' => __( 'Kazakhstan', 'pascommerce' ),
            'KE' => __( 'Kenya', 'pascommerce' ),
            'KI' => __( 'Kiribati', 'pascommerce' ),
            'KP' => __( 'Korea (North)', 'pascommerce' ),
            'KR' => __( 'Korea (South)', 'pascommerce' ),
            'KW' => __( 'Kuwait', 'pascommerce' ),
            'KG' => __( 'Kyrgyzstan', 'pascommerce' ),
            'LA' => __( 'Lao People\'s Democratic Republic', 'pascommerce' ),
            'LV' => __( 'Latvia', 'pascommerce' ),
            'LB' => __( 'Lebanon', 'pascommerce' ),
            'LS' => __( 'Lesotho', 'pascommerce' ),
            'LR' => __( 'Liberia', 'pascommerce' ),
            'LY' => __( 'Libya', 'pascommerce' ),
            'LI' => __( 'Liechtenstein', 'pascommerce' ),
            'LT' => __( 'Lithuania', 'pascommerce' ),
            'LU' => __( 'Luxembourg', 'pascommerce' ),
            'MO' => __( 'Macao', 'pascommerce' ),
            'MG' => __( 'Madagascar', 'pascommerce' ),
            'MW' => __( 'Malawi', 'pascommerce' ),
            'MY' => __( 'Malaysia', 'pascommerce' ),
            'MV' => __( 'Maldives', 'pascommerce' ),
            'ML' => __( 'Mali', 'pascommerce' ),
            'MT' => __( 'Malta', 'pascommerce' ),
            'MH' => __( 'Marshall Islands', 'pascommerce' ),
            'MQ' => __( 'Martinique', 'pascommerce' ),
            'MR' => __( 'Mauritania', 'pascommerce' ),
            'MU' => __( 'Mauritius', 'pascommerce' ),
            'YT' => __( 'Mayotte', 'pascommerce' ),
            'MX' => __( 'Mexico', 'pascommerce' ),
            'FM' => __( 'Micronesia', 'pascommerce' ),
            'MD' => __( 'Moldova', 'pascommerce' ),
            'MC' => __( 'Monaco', 'pascommerce' ),
            'MN' => __( 'Mongolia', 'pascommerce' ),
            'ME' => __( 'Montenegro', 'pascommerce' ),
            'MS' => __( 'Montserrat', 'pascommerce' ),
            'MA' => __( 'Morocco', 'pascommerce' ),
            'MZ' => __( 'Mozambique', 'pascommerce' ),
            'MM' => __( 'Myanmar', 'pascommerce' ),
            'NA' => __( 'Namibia', 'pascommerce' ),
            'NR' => __( 'Nauru', 'pascommerce' ),
            'NP' => __( 'Nepal', 'pascommerce' ),
            'NL' => __( 'Netherlands', 'pascommerce' ),
            'NC' => __( 'New Caledonia', 'pascommerce' ),
            'NZ' => __( 'New Zealand', 'pascommerce' ),
            'NI' => __( 'Nicaragua', 'pascommerce' ),
            'NE' => __( 'Niger', 'pascommerce' ),
            'NG' => __( 'Nigeria', 'pascommerce' ),
            'NU' => __( 'Niue', 'pascommerce' ),
            'NF' => __( 'Norfolk Island', 'pascommerce' ),
            'MK' => __( 'North Macedonia', 'pascommerce' ),
            'MP' => __( 'Northern Mariana Islands', 'pascommerce' ),
            'NO' => __( 'Norway', 'pascommerce' ),
            'OM' => __( 'Oman', 'pascommerce' ),
            'PK' => __( 'Pakistan', 'pascommerce' ),
            'PW' => __( 'Palau', 'pascommerce' ),
            'PS' => __( 'Palestine', 'pascommerce' ),
            'PA' => __( 'Panama', 'pascommerce' ),
            'PG' => __( 'Papua New Guinea', 'pascommerce' ),
            'PY' => __( 'Paraguay', 'pascommerce' ),
            'PE' => __( 'Peru', 'pascommerce' ),
            'PH' => __( 'Philippines', 'pascommerce' ),
            'PN' => __( 'Pitcairn', 'pascommerce' ),
            'PL' => __( 'Poland', 'pascommerce' ),
            'PT' => __( 'Portugal', 'pascommerce' ),
            'PR' => __( 'Puerto Rico', 'pascommerce' ),
            'QA' => __( 'Qatar', 'pascommerce' ),
            'RE' => __( 'Réunion', 'pascommerce' ),
            'RO' => __( 'Romania', 'pascommerce' ),
            'RU' => __( 'Russia', 'pascommerce' ),
            'RW' => __( 'Rwanda', 'pascommerce' ),
            'BL' => __( 'Saint Barthélemy', 'pascommerce' ),
            'SH' => __( 'Saint Helena, Ascension and Tristan da Cunha', 'pascommerce' ),
            'KN' => __( 'Saint Kitts and Nevis', 'pascommerce' ),
            'LC' => __( 'Saint Lucia', 'pascommerce' ),
            'MF' => __( 'Saint Martin (French part)', 'pascommerce' ),
            'PM' => __( 'Saint Pierre and Miquelon', 'pascommerce' ),
            'VC' => __( 'Saint Vincent and the Grenadines', 'pascommerce' ),
            'WS' => __( 'Samoa', 'pascommerce' ),
            'SM' => __( 'San Marino', 'pascommerce' ),
            'ST' => __( 'Sao Tome and Principe', 'pascommerce' ),
            'SA' => __( 'Saudi Arabia', 'pascommerce' ),
            'SN' => __( 'Senegal', 'pascommerce' ),
            'RS' => __( 'Serbia', 'pascommerce' ),
            'SC' => __( 'Seychelles', 'pascommerce' ),
            'SL' => __( 'Sierra Leone', 'pascommerce' ),
            'SG' => __( 'Singapore', 'pascommerce' ),
            'SX' => __( 'Sint Maarten (Dutch part)', 'pascommerce' ),
            'SK' => __( 'Slovakia', 'pascommerce' ),
            'SI' => __( 'Slovenia', 'pascommerce' ),
            'SB' => __( 'Solomon Islands', 'pascommerce' ),
            'SO' => __( 'Somalia', 'pascommerce' ),
            'ZA' => __( 'South Africa', 'pascommerce' ),
            'GS' => __( 'South Georgia and the South Sandwich Islands', 'pascommerce' ),
            'SS' => __( 'South Sudan', 'pascommerce' ),
            'ES' => __( 'Spain', 'pascommerce' ),
            'LK' => __( 'Sri Lanka', 'pascommerce' ),
            'SD' => __( 'Sudan', 'pascommerce' ),
            'SR' => __( 'Suriname', 'pascommerce' ),
            'SJ' => __( 'Svalbard and Jan Mayen', 'pascommerce' ),
            'SE' => __( 'Sweden', 'pascommerce' ),
            'CH' => __( 'Switzerland', 'pascommerce' ),
            'SY' => __( 'Syrian Arab Republic', 'pascommerce' ),
            'TW' => __( 'Taiwan', 'pascommerce' ),
            'TJ' => __( 'Tajikistan', 'pascommerce' ),
            'TZ' => __( 'Tanzania', 'pascommerce' ),
            'TH' => __( 'Thailand', 'pascommerce' ),
            'TL' => __( 'Timor-Leste', 'pascommerce' ),
            'TG' => __( 'Togo', 'pascommerce' ),
            'TK' => __( 'Tokelau', 'pascommerce' ),
            'TO' => __( 'Tonga', 'pascommerce' ),
            'TT' => __( 'Trinidad and Tobago', 'pascommerce' ),
            'TN' => __( 'Tunisia', 'pascommerce' ),
            'TR' => __( 'Turkey', 'pascommerce' ),
            'TM' => __( 'Turkmenistan', 'pascommerce' ),
            'TC' => __( 'Turks and Caicos Islands', 'pascommerce' ),
            'TV' => __( 'Tuvalu', 'pascommerce' ),
            'UG' => __( 'Uganda', 'pascommerce' ),
            'UA' => __( 'Ukraine', 'pascommerce' ),
            'AE' => __( 'United Arab Emirates', 'pascommerce' ),
            'GB' => __( 'United Kingdom', 'pascommerce' ),
            'US' => __( 'United States', 'pascommerce' ),
            'UY' => __( 'Uruguay', 'pascommerce' ),
            'UZ' => __( 'Uzbekistan', 'pascommerce' ),
            'VU' => __( 'Vanuatu', 'pascommerce' ),
            'VE' => __( 'Venezuela', 'pascommerce' ),
            'VN' => __( 'Vietnam', 'pascommerce' ),
            'VG' => __( 'Virgin Islands (British)', 'pascommerce' ),
            'VI' => __( 'Virgin Islands (U.S.)', 'pascommerce' ),
            'WF' => __( 'Wallis and Futuna', 'pascommerce' ),
            'EH' => __( 'Western Sahara', 'pascommerce' ),
            'YE' => __( 'Yemen', 'pascommerce' ),
            'ZM' => __( 'Zambia', 'pascommerce' ),
            'ZW' => __( 'Zimbabwe', 'pascommerce' ),
        );

        // Filter ini memungkinkan Addon (seperti RajaOngkir) untuk memodifikasi daftar negara.
        // Contoh: RajaOngkir mungkin hanya ingin menampilkan 'ID' saja untuk menyederhanakan.
        return apply_filters( 'pc_countries', $countries );
    }

    /**
     * Get States/Provinces for a Country
     * Framework provides structure, Addons provide data.
     * * @param string $country_code (e.g., 'ID', 'US')
     * @return array (Code => Name)
     */
    public static function get_states( $country_code = '' ) {
        if ( empty( $country_code ) ) {
            $country_code = get_option( 'pc_store_country', 'ID' );
        }

        // Default: kosong (karena data provinsi seluruh dunia sangat besar).
        // Addon seperti "Pascommerce - RajaOngkir" akan meng-hook filter ini 
        // untuk mengisi data provinsi Indonesia secara real-time atau dari database-nya.
        $states = array();

        return apply_filters( 'pc_states', $states, $country_code );
    }

    /**
     * Get All Currencies (Format: Code => Name (Symbol))
     */
    public static function get_currencies() {
        return apply_filters( 'pc_currencies', array(
            'IDR' => __( 'Indonesian Rupiah (Rp)', 'pascommerce' ),
            'USD' => __( 'US Dollar ($)', 'pascommerce' ),
            'SGD' => __( 'Singapore Dollar (S$)', 'pascommerce' ),
            'MYR' => __( 'Malaysian Ringgit (RM)', 'pascommerce' ),
            'AUD' => __( 'Australian Dollar ($)', 'pascommerce' ),
            'EUR' => __( 'Euro (€)', 'pascommerce' ),
            'GBP' => __( 'Pound Sterling (£)', 'pascommerce' ),
            'JPY' => __( 'Japanese Yen (¥)', 'pascommerce' ),
            'CNY' => __( 'Chinese Yuan (¥)', 'pascommerce' ),
            'KRW' => __( 'South Korean Won (₩)', 'pascommerce' ),
            'THB' => __( 'Thai Baht (฿)', 'pascommerce' ),
            'VND' => __( 'Vietnamese Dong (₫)', 'pascommerce' ),
            'PHP' => __( 'Philippine Peso (₱)', 'pascommerce' ),
            'INR' => __( 'Indian Rupee (₹)', 'pascommerce' ),
            'CAD' => __( 'Canadian Dollar ($)', 'pascommerce' ),
        ));
    }

    /**
     * Get Currency Symbol by Code
     */
    public static function get_currency_symbol( $currency = '' ) {
        if ( ! $currency ) {
            $currency = get_option( 'pc_currency', 'IDR' );
        }

        $symbols = array(
            'IDR' => 'Rp', 'USD' => '$', 'SGD' => 'S$', 'MYR' => 'RM',
            'AUD' => '$',  'EUR' => '€', 'GBP' => '£',  'JPY' => '¥',
            'CNY' => '¥',  'KRW' => '₩', 'THB' => '฿',  'VND' => '₫',
            'PHP' => '₱',  'INR' => '₹', 'CAD' => '$',
        );

        $symbol = isset( $symbols[ $currency ] ) ? $symbols[ $currency ] : $currency;
        return apply_filters( 'pc_currency_symbol', $symbol, $currency );
    }
}